spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  profiles:
    active: test
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration

## rpdpymnt Properties
rpdpymnt:
  jwt:
    secret: JWTSuperSecretKey
    expirationInMs: 604800000
    expirationVodagrafRegInMs: 2629800000

logging:
  config: classpath:logback-spring.xml
  level:
    com.rpdpymnt: DEBUG
