spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch.matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: "Rpdpymnt Reporting"
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true

## rpdpymnt Properties
rpdpymnt:
  jwt:
    secret: JWTSuperSecretKey
    expirationInMs: 604800000
    expirationVodagrafRegInMs: 2629800000

logging:
  config: classpath:logback-spring.xml
  level:
    com.rpdpymnt: DEBUG
